# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x08\x63heckout\"\xdf\x01\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x14\n\x0cuser_contact\x18\x03 \x01(\t\x12\x1d\n\x05items\x18\x04 \x03(\x0b\x32\x0e.checkout.Item\x12\x1a\n\x12\x63redit_card_number\x18\x05 \x01(\t\x12\x1a\n\x12\x63redit_card_expiry\x18\x06 \x01(\t\x12\x17\n\x0f\x63redit_card_cvv\x18\x07 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x08 \x01(\x01\x12\x15\n\rgift_wrapping\x18\t \x01(\x08\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"/\n\x0b\x46raudResult\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"=\n\x12VerificationResult\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"?\n\x0fSuggestionsList\x12,\n\x0bsuggestions\x18\x01 \x03(\x0b\x32\x17.checkout.SuggestedBook\"?\n\rSuggestedBook\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t2H\n\x0e\x46raudDetection\x12\x36\n\nCheckFraud\x12\x0f.checkout.Order\x1a\x15.checkout.FraudResult\"\x00\x32Y\n\x17TransactionVerification\x12>\n\x0bVerifyOrder\x12\x0f.checkout.Order\x1a\x1c.checkout.VerificationResult\"\x00\x32M\n\x0bSuggestions\x12>\n\x0eGetSuggestions\x12\x0f.checkout.Order\x1a\x19.checkout.SuggestionsList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=36
  _globals['_ORDER']._serialized_end=259
  _globals['_ITEM']._serialized_start=261
  _globals['_ITEM']._serialized_end=299
  _globals['_FRAUDRESULT']._serialized_start=301
  _globals['_FRAUDRESULT']._serialized_end=348
  _globals['_VERIFICATIONRESULT']._serialized_start=350
  _globals['_VERIFICATIONRESULT']._serialized_end=411
  _globals['_SUGGESTIONSLIST']._serialized_start=413
  _globals['_SUGGESTIONSLIST']._serialized_end=476
  _globals['_SUGGESTEDBOOK']._serialized_start=478
  _globals['_SUGGESTEDBOOK']._serialized_end=541
  _globals['_FRAUDDETECTION']._serialized_start=543
  _globals['_FRAUDDETECTION']._serialized_end=615
  _globals['_TRANSACTIONVERIFICATION']._serialized_start=617
  _globals['_TRANSACTIONVERIFICATION']._serialized_end=706
  _globals['_SUGGESTIONS']._serialized_start=708
  _globals['_SUGGESTIONS']._serialized_end=785
# @@protoc_insertion_point(module_scope)
