# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fraud_detection_pb2 as fraud__detection__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fraud_detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FraudDetectionStub(object):
    """Fraud Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckFraud = channel.unary_unary(
                '/checkout.FraudDetection/CheckFraud',
                request_serializer=fraud__detection__pb2.Order.SerializeToString,
                response_deserializer=fraud__detection__pb2.FraudResult.FromString,
                _registered_method=True)


class FraudDetectionServicer(object):
    """Fraud Service
    """

    def CheckFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckFraud,
                    request_deserializer=fraud__detection__pb2.Order.FromString,
                    response_serializer=fraud__detection__pb2.FraudResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checkout.FraudDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('checkout.FraudDetection', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FraudDetection(object):
    """Fraud Service
    """

    @staticmethod
    def CheckFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkout.FraudDetection/CheckFraud',
            fraud__detection__pb2.Order.SerializeToString,
            fraud__detection__pb2.FraudResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TransactionVerificationStub(object):
    """Transaction Verification Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyOrder = channel.unary_unary(
                '/checkout.TransactionVerification/VerifyOrder',
                request_serializer=fraud__detection__pb2.Order.SerializeToString,
                response_deserializer=fraud__detection__pb2.VerificationResult.FromString,
                _registered_method=True)


class TransactionVerificationServicer(object):
    """Transaction Verification Service
    """

    def VerifyOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionVerificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOrder,
                    request_deserializer=fraud__detection__pb2.Order.FromString,
                    response_serializer=fraud__detection__pb2.VerificationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checkout.TransactionVerification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('checkout.TransactionVerification', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionVerification(object):
    """Transaction Verification Service
    """

    @staticmethod
    def VerifyOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkout.TransactionVerification/VerifyOrder',
            fraud__detection__pb2.Order.SerializeToString,
            fraud__detection__pb2.VerificationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SuggestionsStub(object):
    """Suggestions Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSuggestions = channel.unary_unary(
                '/checkout.Suggestions/GetSuggestions',
                request_serializer=fraud__detection__pb2.Order.SerializeToString,
                response_deserializer=fraud__detection__pb2.SuggestionsList.FromString,
                _registered_method=True)


class SuggestionsServicer(object):
    """Suggestions Service
    """

    def GetSuggestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSuggestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSuggestions,
                    request_deserializer=fraud__detection__pb2.Order.FromString,
                    response_serializer=fraud__detection__pb2.SuggestionsList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checkout.Suggestions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('checkout.Suggestions', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Suggestions(object):
    """Suggestions Service
    """

    @staticmethod
    def GetSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkout.Suggestions/GetSuggestions',
            fraud__detection__pb2.Order.SerializeToString,
            fraud__detection__pb2.SuggestionsList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
