# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\x12\x05\x62ooks\"\x18\n\x07ReadReq\x12\r\n\x05title\x18\x01 \x01(\t\"\x19\n\x08ReadResp\x12\r\n\x05stock\x18\x01 \x01(\x05\",\n\x08WriteReq\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\"\x1c\n\tWriteResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\"?\n\nPrepareReq\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x1f\n\x06staged\x18\x02 \x03(\x0b\x32\x0f.books.WriteReq\"\x1c\n\x0bPrepareResp\x12\r\n\x05ready\x18\x01 \x01(\x08\"\x1d\n\tCommitReq\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\x1d\n\nCommitResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1c\n\x08\x41\x62ortReq\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\x1c\n\tAbortResp\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x32\xeb\x01\n\x07\x42ooksDB\x12\'\n\x04Read\x12\x0e.books.ReadReq\x1a\x0f.books.ReadResp\x12*\n\x05Write\x12\x0f.books.WriteReq\x1a\x10.books.WriteResp\x12\x30\n\x07Prepare\x12\x11.books.PrepareReq\x1a\x12.books.PrepareResp\x12-\n\x06\x43ommit\x12\x10.books.CommitReq\x1a\x11.books.CommitResp\x12*\n\x05\x41\x62ort\x12\x0f.books.AbortReq\x1a\x10.books.AbortRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_READREQ']._serialized_start=22
  _globals['_READREQ']._serialized_end=46
  _globals['_READRESP']._serialized_start=48
  _globals['_READRESP']._serialized_end=73
  _globals['_WRITEREQ']._serialized_start=75
  _globals['_WRITEREQ']._serialized_end=119
  _globals['_WRITERESP']._serialized_start=121
  _globals['_WRITERESP']._serialized_end=149
  _globals['_PREPAREREQ']._serialized_start=151
  _globals['_PREPAREREQ']._serialized_end=214
  _globals['_PREPARERESP']._serialized_start=216
  _globals['_PREPARERESP']._serialized_end=244
  _globals['_COMMITREQ']._serialized_start=246
  _globals['_COMMITREQ']._serialized_end=275
  _globals['_COMMITRESP']._serialized_start=277
  _globals['_COMMITRESP']._serialized_end=306
  _globals['_ABORTREQ']._serialized_start=308
  _globals['_ABORTREQ']._serialized_end=336
  _globals['_ABORTRESP']._serialized_start=338
  _globals['_ABORTRESP']._serialized_end=366
  _globals['_BOOKSDB']._serialized_start=369
  _globals['_BOOKSDB']._serialized_end=604
# @@protoc_insertion_point(module_scope)
