# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import books_pb2 as books__pb2


class BooksDBStub(object):
    """----------  simple KV API  ---------- 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/books.BooksDB/Read',
                request_serializer=books__pb2.ReadReq.SerializeToString,
                response_deserializer=books__pb2.ReadResp.FromString,
                )
        self.Write = channel.unary_unary(
                '/books.BooksDB/Write',
                request_serializer=books__pb2.WriteReq.SerializeToString,
                response_deserializer=books__pb2.WriteResp.FromString,
                )
        self.Prepare = channel.unary_unary(
                '/books.BooksDB/Prepare',
                request_serializer=books__pb2.PrepareReq.SerializeToString,
                response_deserializer=books__pb2.PrepareResp.FromString,
                )
        self.Commit = channel.unary_unary(
                '/books.BooksDB/Commit',
                request_serializer=books__pb2.CommitReq.SerializeToString,
                response_deserializer=books__pb2.CommitResp.FromString,
                )
        self.Abort = channel.unary_unary(
                '/books.BooksDB/Abort',
                request_serializer=books__pb2.AbortReq.SerializeToString,
                response_deserializer=books__pb2.AbortResp.FromString,
                )


class BooksDBServicer(object):
    """----------  simple KV API  ---------- 
    """

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prepare(self, request, context):
        """-----  2‑PC participant RPCs  ----- 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=books__pb2.ReadReq.FromString,
                    response_serializer=books__pb2.ReadResp.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=books__pb2.WriteReq.FromString,
                    response_serializer=books__pb2.WriteResp.SerializeToString,
            ),
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=books__pb2.PrepareReq.FromString,
                    response_serializer=books__pb2.PrepareResp.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=books__pb2.CommitReq.FromString,
                    response_serializer=books__pb2.CommitResp.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=books__pb2.AbortReq.FromString,
                    response_serializer=books__pb2.AbortResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books.BooksDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BooksDB(object):
    """----------  simple KV API  ---------- 
    """

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.BooksDB/Read',
            books__pb2.ReadReq.SerializeToString,
            books__pb2.ReadResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.BooksDB/Write',
            books__pb2.WriteReq.SerializeToString,
            books__pb2.WriteResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.BooksDB/Prepare',
            books__pb2.PrepareReq.SerializeToString,
            books__pb2.PrepareResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.BooksDB/Commit',
            books__pb2.CommitReq.SerializeToString,
            books__pb2.CommitResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.BooksDB/Abort',
            books__pb2.AbortReq.SerializeToString,
            books__pb2.AbortResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
