# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\".\n\nPrepareReq\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"\x1c\n\x0bPrepareResp\x12\r\n\x05ready\x18\x01 \x01(\x08\"\x1d\n\tCommitReq\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\x1d\n\nCommitResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1c\n\x08\x41\x62ortReq\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\x1c\n\tAbortResp\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x32\xa2\x01\n\x07Payment\x12\x34\n\x07Prepare\x12\x13.payment.PrepareReq\x1a\x14.payment.PrepareResp\x12\x31\n\x06\x43ommit\x12\x12.payment.CommitReq\x1a\x13.payment.CommitResp\x12.\n\x05\x41\x62ort\x12\x11.payment.AbortReq\x1a\x12.payment.AbortRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREPAREREQ']._serialized_start=26
  _globals['_PREPAREREQ']._serialized_end=72
  _globals['_PREPARERESP']._serialized_start=74
  _globals['_PREPARERESP']._serialized_end=102
  _globals['_COMMITREQ']._serialized_start=104
  _globals['_COMMITREQ']._serialized_end=133
  _globals['_COMMITRESP']._serialized_start=135
  _globals['_COMMITRESP']._serialized_end=164
  _globals['_ABORTREQ']._serialized_start=166
  _globals['_ABORTREQ']._serialized_end=194
  _globals['_ABORTRESP']._serialized_start=196
  _globals['_ABORTRESP']._serialized_end=224
  _globals['_PAYMENT']._serialized_start=227
  _globals['_PAYMENT']._serialized_end=389
# @@protoc_insertion_point(module_scope)
