# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: election.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'election.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65lection.proto\x12\x08\x65lection\"1\n\x0f\x45lectionRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty2K\n\x08\x45lection\x12?\n\x0f\x45lectionMessage\x12\x19.election.ElectionRequest\x1a\x0f.election.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'election_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONREQUEST']._serialized_start=28
  _globals['_ELECTIONREQUEST']._serialized_end=77
  _globals['_EMPTY']._serialized_start=79
  _globals['_EMPTY']._serialized_end=86
  _globals['_ELECTION']._serialized_start=88
  _globals['_ELECTION']._serialized_end=163
# @@protoc_insertion_point(module_scope)
