# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import checkout_pb2 as checkout__pb2


class VerificationServiceStub(object):
    """Transaction Verification
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitOrder = channel.unary_unary(
                '/checkout.VerificationService/InitOrder',
                request_serializer=checkout__pb2.OrderInitRequest.SerializeToString,
                response_deserializer=checkout__pb2.OrderInitResponse.FromString,
                )
        self.VerifyItems = channel.unary_unary(
                '/checkout.VerificationService/VerifyItems',
                request_serializer=checkout__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=checkout__pb2.OrderEventResponse.FromString,
                )
        self.VerifyUserData = channel.unary_unary(
                '/checkout.VerificationService/VerifyUserData',
                request_serializer=checkout__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=checkout__pb2.OrderEventResponse.FromString,
                )
        self.VerifyCreditCard = channel.unary_unary(
                '/checkout.VerificationService/VerifyCreditCard',
                request_serializer=checkout__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=checkout__pb2.OrderEventResponse.FromString,
                )
        self.ClearOrder = channel.unary_unary(
                '/checkout.VerificationService/ClearOrder',
                request_serializer=checkout__pb2.OrderClearRequest.SerializeToString,
                response_deserializer=checkout__pb2.OrderClearResponse.FromString,
                )


class VerificationServiceServicer(object):
    """Transaction Verification
    """

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCreditCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=checkout__pb2.OrderInitRequest.FromString,
                    response_serializer=checkout__pb2.OrderInitResponse.SerializeToString,
            ),
            'VerifyItems': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyItems,
                    request_deserializer=checkout__pb2.OrderEventRequest.FromString,
                    response_serializer=checkout__pb2.OrderEventResponse.SerializeToString,
            ),
            'VerifyUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyUserData,
                    request_deserializer=checkout__pb2.OrderEventRequest.FromString,
                    response_serializer=checkout__pb2.OrderEventResponse.SerializeToString,
            ),
            'VerifyCreditCard': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCreditCard,
                    request_deserializer=checkout__pb2.OrderEventRequest.FromString,
                    response_serializer=checkout__pb2.OrderEventResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=checkout__pb2.OrderClearRequest.FromString,
                    response_serializer=checkout__pb2.OrderClearResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checkout.VerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VerificationService(object):
    """Transaction Verification
    """

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkout.VerificationService/InitOrder',
            checkout__pb2.OrderInitRequest.SerializeToString,
            checkout__pb2.OrderInitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkout.VerificationService/VerifyItems',
            checkout__pb2.OrderEventRequest.SerializeToString,
            checkout__pb2.OrderEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkout.VerificationService/VerifyUserData',
            checkout__pb2.OrderEventRequest.SerializeToString,
            checkout__pb2.OrderEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyCreditCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkout.VerificationService/VerifyCreditCard',
            checkout__pb2.OrderEventRequest.SerializeToString,
            checkout__pb2.OrderEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkout.VerificationService/ClearOrder',
            checkout__pb2.OrderClearRequest.SerializeToString,
            checkout__pb2.OrderClearResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class FraudServiceStub(object):
    """Fraud Detection
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitOrder = channel.unary_unary(
                '/checkout.FraudService/InitOrder',
                request_serializer=checkout__pb2.OrderInitRequest.SerializeToString,
                response_deserializer=checkout__pb2.OrderInitResponse.FromString,
                )
        self.CheckUserFraud = channel.unary_unary(
                '/checkout.FraudService/CheckUserFraud',
                request_serializer=checkout__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=checkout__pb2.OrderEventResponse.FromString,
                )
        self.CheckCreditCardFraud = channel.unary_unary(
                '/checkout.FraudService/CheckCreditCardFraud',
                request_serializer=checkout__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=checkout__pb2.OrderEventResponse.FromString,
                )
        self.ClearOrder = channel.unary_unary(
                '/checkout.FraudService/ClearOrder',
                request_serializer=checkout__pb2.OrderClearRequest.SerializeToString,
                response_deserializer=checkout__pb2.OrderClearResponse.FromString,
                )


class FraudServiceServicer(object):
    """Fraud Detection
    """

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCreditCardFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=checkout__pb2.OrderInitRequest.FromString,
                    response_serializer=checkout__pb2.OrderInitResponse.SerializeToString,
            ),
            'CheckUserFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserFraud,
                    request_deserializer=checkout__pb2.OrderEventRequest.FromString,
                    response_serializer=checkout__pb2.OrderEventResponse.SerializeToString,
            ),
            'CheckCreditCardFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCreditCardFraud,
                    request_deserializer=checkout__pb2.OrderEventRequest.FromString,
                    response_serializer=checkout__pb2.OrderEventResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=checkout__pb2.OrderClearRequest.FromString,
                    response_serializer=checkout__pb2.OrderClearResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checkout.FraudService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FraudService(object):
    """Fraud Detection
    """

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkout.FraudService/InitOrder',
            checkout__pb2.OrderInitRequest.SerializeToString,
            checkout__pb2.OrderInitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckUserFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkout.FraudService/CheckUserFraud',
            checkout__pb2.OrderEventRequest.SerializeToString,
            checkout__pb2.OrderEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckCreditCardFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkout.FraudService/CheckCreditCardFraud',
            checkout__pb2.OrderEventRequest.SerializeToString,
            checkout__pb2.OrderEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkout.FraudService/ClearOrder',
            checkout__pb2.OrderClearRequest.SerializeToString,
            checkout__pb2.OrderClearResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SuggestionsServiceStub(object):
    """Suggestions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitOrder = channel.unary_unary(
                '/checkout.SuggestionsService/InitOrder',
                request_serializer=checkout__pb2.OrderInitRequest.SerializeToString,
                response_deserializer=checkout__pb2.OrderInitResponse.FromString,
                )
        self.GenerateSuggestions = channel.unary_unary(
                '/checkout.SuggestionsService/GenerateSuggestions',
                request_serializer=checkout__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=checkout__pb2.OrderEventResponse.FromString,
                )
        self.ClearOrder = channel.unary_unary(
                '/checkout.SuggestionsService/ClearOrder',
                request_serializer=checkout__pb2.OrderClearRequest.SerializeToString,
                response_deserializer=checkout__pb2.OrderClearResponse.FromString,
                )


class SuggestionsServiceServicer(object):
    """Suggestions
    """

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSuggestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=checkout__pb2.OrderInitRequest.FromString,
                    response_serializer=checkout__pb2.OrderInitResponse.SerializeToString,
            ),
            'GenerateSuggestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSuggestions,
                    request_deserializer=checkout__pb2.OrderEventRequest.FromString,
                    response_serializer=checkout__pb2.OrderEventResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=checkout__pb2.OrderClearRequest.FromString,
                    response_serializer=checkout__pb2.OrderClearResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checkout.SuggestionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SuggestionsService(object):
    """Suggestions
    """

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkout.SuggestionsService/InitOrder',
            checkout__pb2.OrderInitRequest.SerializeToString,
            checkout__pb2.OrderInitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkout.SuggestionsService/GenerateSuggestions',
            checkout__pb2.OrderEventRequest.SerializeToString,
            checkout__pb2.OrderEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkout.SuggestionsService/ClearOrder',
            checkout__pb2.OrderClearRequest.SerializeToString,
            checkout__pb2.OrderClearResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
