# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkout.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63heckout.proto\x12\x08\x63heckout\"5\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"\xd2\x01\n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0btotal_price\x18\x02 \x01(\x01\x12\x1d\n\x05items\x18\x03 \x03(\x0b\x32\x0e.checkout.Item\x12\x11\n\tuser_name\x18\x04 \x01(\t\x12\x14\n\x0cuser_contact\x18\x05 \x01(\t\x12\x1a\n\x12\x63redit_card_number\x18\x06 \x01(\t\x12\x1e\n\x16\x63redit_card_expiration\x18\x07 \x01(\t\x12\x17\n\x0f\x63redit_card_cvv\x18\x08 \x01(\t\"1\n\rFraudResponse\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"9\n\x14VerificationResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"C\n\x13SuggestionsResponse\x12,\n\x0bsuggestions\x18\x01 \x03(\x0b\x32\x17.checkout.SuggestedBook\"?\n\rSuggestedBook\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t2M\n\x0c\x46raudService\x12=\n\nCheckFraud\x12\x16.checkout.OrderRequest\x1a\x17.checkout.FraudResponse2\\\n\x13VerificationService\x12\x45\n\x0bVerifyOrder\x12\x16.checkout.OrderRequest\x1a\x1e.checkout.VerificationResponse2]\n\x12SuggestionsService\x12G\n\x0eGetSuggestions\x12\x16.checkout.OrderRequest\x1a\x1d.checkout.SuggestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checkout_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEM']._serialized_start=28
  _globals['_ITEM']._serialized_end=81
  _globals['_ORDERREQUEST']._serialized_start=84
  _globals['_ORDERREQUEST']._serialized_end=294
  _globals['_FRAUDRESPONSE']._serialized_start=296
  _globals['_FRAUDRESPONSE']._serialized_end=345
  _globals['_VERIFICATIONRESPONSE']._serialized_start=347
  _globals['_VERIFICATIONRESPONSE']._serialized_end=404
  _globals['_SUGGESTIONSRESPONSE']._serialized_start=406
  _globals['_SUGGESTIONSRESPONSE']._serialized_end=473
  _globals['_SUGGESTEDBOOK']._serialized_start=475
  _globals['_SUGGESTEDBOOK']._serialized_end=538
  _globals['_FRAUDSERVICE']._serialized_start=540
  _globals['_FRAUDSERVICE']._serialized_end=617
  _globals['_VERIFICATIONSERVICE']._serialized_start=619
  _globals['_VERIFICATIONSERVICE']._serialized_end=711
  _globals['_SUGGESTIONSSERVICE']._serialized_start=713
  _globals['_SUGGESTIONSSERVICE']._serialized_end=806
# @@protoc_insertion_point(module_scope)
